config/routes.rb
Bulleit::Application.routes.draw do
  root :to => "pages#home"
  get "/login" => "oauth#login"
  get "/authorize" => "oauth#authorize"
  post "/athletes/create" => "athletes#create"
  get "/athletes/history" => "athletes#history", :as => "new_history"
  post "/athletes/history" => "athletes#create_history", :as=> "create_history"
  get "/athletes/goal" => "athletes#goal", :as => "new_goal"
  post "/athletes/goal" => "athletes#create_goal", :as => "create_goal"
  match "signout", to: 'oauth#destroy', via: :delete

  get '/schedule' => "schedule#schedule"
  get '/schedule/current' => "schedule#current_week"
  get '/templates/:id/generate' => "running_templates#new_instance", :as => "new_instance"
  post '/templates/:id/generate' => "running_templates#create_instance", :as => "create_instance"

  resources :templates, :controller => :running_templates do
    resources :weeks, :controller => :running_template_weeks, :only => [:edit, :update]
  end

end

app/models/running_template_week.rb
class RunningTemplateWeek < ActiveRecord::Base
  attr_accessible :running_template_id, :distance_percent, :sequence, :description

  belongs_to :running_template
  has_many :running_template_workouts
  default_scope :order => "running_template_weeks.sequence ASC"
  
  def generate(athlete, start_of_week, weekly_schedule)
  	week = ScheduleWeek.new(athlete_id: athlete.id,
  							total_distance: (self.distance_percent * self.running_template.distance_per_week)/100,
  							description: self.description,
  							start_date:start_of_week)
  	week.save
  	(0..6).each do |wday|
  		current_day = start_of_week + wday
  		if weekly_schedule[wday] == "workout1"
  			running_template_workouts[0].generate(week, athlete, current_day)
  		elsif weekly_schedule[wday] == "workout2"
  			running_template_workouts[1].generate(week, athlete, current_day)
  		elsif weekly_schedule[wday] == "off"
  			workout = Workout.new(athlete_id:athlete.id,
  								  schedule_week_id: week.id,
  								  workout_type:3,
  								  date:current_day,
  								  description:"Off Day")
  			workout.save
  		else
  			workout = Workout.new(athlete_id:athlete.id,
  								  schedule_week_id: week.id,
  								  workout_type:2,
  								  total_distance: (week.total_distance - self.running_template_workouts.sum(:total_distance)) * weekly_schedule[wday],
  								  date:current_day,
  								  description:"Easy Day")
  			workout.save
  		end
  	end
  end
end

app/controllers/running_template_weeks_controller.rb
class RunningTemplateWeeksController < ApplicationController
	include RunningTemplateWeekHelper
	def edit
		@template, @week = get_week(params[:template_id], params[:id])
	end

	def update
		logger = Logger.new STDOUT
		@errors = []
		@template, @week = get_week(params[:template_id], params[:id])
		@week.distance_percent = params[:week][:distance_percent]
		@week.description = params[:week][:description]
		if @week.save
			params[:workout].each do |id, workout|
				if RunningTemplateWorkout.exists?(id)
					@workout = RunningTemplateWorkout.find(id)
					@workout.total_distance = workout[:total_distance]
					@workout.description = workout[:description]
					if @workout.save && @workout.running_template_workout_legs.delete_all
						workout[:legs].each do |sequence, leg|
							logger.info sequence
							logger.info leg
							if leg[:active] == "1"
								@leg = RunningTemplateWorkoutLeg.new(repetitions: leg[:repetitions],
																	 distance: leg[:distance],
																	 distance_type: leg[:distance_type],
																	 pace_type: leg[:pace_type],
																	 recovery: leg[:recovery],
																	 sequence: sequence,
																	 running_template_workout_id: @workout.id)
								if !@leg.save
									@leg.errors.full_message.each do |msg|  @errors << msg  end
								end
							end
						end
					else
						@workout.errors.full_message.each do |msg| @errors << msg end
					end
				end
			end
		else
			@week.errors.full_message.each  do |msg|  @errors << msg end
		end

		if !@errors.empty?
			render 'edit'
		else
			redirect_to template_path(params[:template_id])
		end
	end

	private
		def get_week(template_id, sequence)
			if RunningTemplate.exists?(template_id)
				template = RunningTemplate.find(template_id)
				if template.running_template_weeks.exists?(:sequence => sequence)
					return template, template.running_template_weeks.find_by_sequence(sequence)
				end
			end
			redirect_to '/404'
		end
end

app/helpers/running_template_week_helper.rb
module RunningTemplateWeekHelper
end

app/views/running_template_weeks/edit.html.erb
<%= render 'shared/athlete_nav' %>
<%= render 'shared/error_messages', errors:@errors %>
<div class="row">
	<div class="span12">
		<ul class="breadcrumb">
		  <li><a href="<%= templates_path  %>">Templates</a> <span class="divider">-</span></li>
		  <li><a href="<%= template_path(@template) %>"><%= @template.name %></a> <span class="divider">-</span></li>
		  <li><a href="<%= edit_week(@template, @week) %>">Edit</a></li>
		</ul>
	</div>
	<div class="span8 offset2">
		<%= form_tag update_week(@template, @week), method: "put", :class => "form-horizontal" do %>
			<legend>Edit <%= @template.name %> - Week <%= @week.sequence %></legend>
			<div class="control-group">
				<label class="control-label" for="distance_percent">Distance Percentage</label>
				<div class="controls">
					<input type="number" class="span1" min="0" max="100" default="100" id="distance_percent" name="week[distance_percent]" value="<%= @week.distance_percent%>"></input>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="week_description">Description</label>
				<textarea rows="3" id="week_description" name="week[description]" value="<%= @week.description %>"></textarea>
			</div>
			<% @week.running_template_workouts.each do |workout| %>
			<hr>
			<h5>Workout</h5>
			<div class="control-group">
				<label class="control-label" for="description">Description</label>
				<input type="text" id="description" name="workout[<%= workout.id %>][description]" value="<%= workout.description %>"></input>
			</div>
			<div class="control-group">
				<label class="control-label" for="total_distance">Total Distance</label>
				<input type="number" id="total_distance" name="workout[<%= workout.id %>][total_distance]" value="<%= workout.total_distance %>"></input>
			</div>
			
			<table id="workout_<%=workout.id %>"class="table table-striped table-condensed">
				<thead>
					<th></th>
					<th>Repetitions</th>
					<th>Distance</th>
					<th>Pace</th>
					<th>Recovery</th>
				</thead>
				<tbody>
				<% (0..6).each do |sequence| %>
					<tr>
					<% if workout.running_template_workout_legs.exists?(sequence: sequence) %>
						<% leg = workout.running_template_workout_legs.find_by_sequence(sequence) %>
						<td><input type="checkbox" id="include" name="workout[<%= workout.id %>][legs][<%= sequence %>][active]" value="1" checked="checked"></input></td>
					<% else %>
						<td><input type="checkbox" id="include" name="workout[<%= workout.id %>][legs][<%= sequence %>][active]" value="1"></input></td>
						<% leg = RunningTemplateWorkoutLeg.new %>
					<% end %>
						<td>
							<input type="number" class="span1" id="repetitions" name="workout[<%= workout.id %>][legs][<%= sequence %>][repetitions]" value="<%= leg.repetitions %>"></input>
						</td>
						<td>
							<input type="number" class="span1" id="distance" name="workout[<%= workout.id %>][legs][<%= sequence %>][distance]" value="<%= leg.distance %>"></input>
							<select class="span2" name="workout[<%= workout.id %>][legs][<%= sequence %>][distance_type]" id="distance_type" value="<%= leg.distance_type %>">
								<%= render 'shared/distance_type_options' %>
							</select>
						</td>
						<td>
							<select class="span2" name="workout[<%= workout.id %>][legs][<%= sequence %>][pace_type]" id="pace_type" value="<%= leg.pace_type %>">
								<option value="<%= PaceType::EASY %>" <% if leg.pace_type == PaceType::EASY %> selected="selected" <% end %> ><%= PaceType.toString(PaceType::EASY) %></option>
								<option value="<%= PaceType::MARATHON %>" <% if leg.pace_type == PaceType::MARATHON %> selected="selected" <% end %> ><%= PaceType.toString(PaceType::MARATHON) %></option>
								<option value="<%= PaceType::THRESHOLD %>" <% if leg.pace_type == PaceType::THRESHOLD %> selected="selected" <% end %> ><%= PaceType.toString(PaceType::THRESHOLD) %></option>
								<option value="<%= PaceType::REP %>" <% if leg.pace_type == PaceType::REP %> selected="selected" <% end %> ><%= PaceType.toString(PaceType::REP) %></option>
							</select>
						</td>
						<td>
							<input type="number" class="span1" id="distance" name="workout[<%= workout.id %>][legs][<%= sequence %>][recovery]" value="<%= leg.recovery %>"></input>
						</td>
						
					</tr>
				<% end %>
				</tbody>
			</table>
			<% end %>
			<div class="form-actions">
			  	<button type="submit" class="btn btn-primary">Save changes</button>
			  	<a type="button" class="btn" href="<%= template_path(@template) %>">Cancel</a>
			</div>
		<% end %>
	</div>
</div>