config/routes.rb
Bulleit::Application.routes.draw do
  root :to => "pages#home"
  get "/login" => "oauth#login"
  get "/authorize" => "oauth#authorize"
  post "/athletes/create" => "athletes#create"
  get "/athletes/history" => "athletes#history", :as => "new_history"
  post "/athletes/history" => "athletes#create_history", :as=> "create_history"
  get "/athletes/goal" => "athletes#goal", :as => "new_goal"
  post "/athletes/goal" => "athletes#create_goal", :as => "create_goal"
  match "signout", to: 'oauth#destroy', via: :delete

  get '/schedule' => "schedule#schedule"
  get '/schedule/current' => "schedule#current_week"
  get '/templates/:id/generate' => "running_templates#new_instance", :as => "new_instance"
  post '/templates/:id/generate' => "running_templates#create_instance", :as => "create_instance"

  resources :templates, :controller => :running_templates do
    resources :weeks, :controller => :running_template_weeks, :only => [:edit, :update]
  end

end

app/models/running_template.rb
class RunningTemplate < ActiveRecord::Base
  attr_accessible :name, :distance, :distance_per_week, :distance_type, :level, :number_of_weeks, :runs_per_week
  has_many :running_template_weeks
  
  def generate(athlete, race_date, weekly_schedule)
  	logger = Logger.new STDOUT
  	logger.info weekly_schedule

  	start_date = calculate_start_date(race_date)
  	self.running_template_weeks.each do |week|
  		start_of_week = start_date + 7 * week.sequence
  		week.generate(athlete, start_of_week, weekly_schedule)
  	end
  end

  private 
  	def calculate_start_date(date_of_race)
  		# start on closest Monday
  		start_date = date_of_race - self.number_of_weeks*7
  		if start_date.wday == 6
        start_date += 2
      elsif start_date.wday == 0
        start_date += 1
      end
  	end
end

app/controllers/running_templates_controller.rb
class RunningTemplatesController < ApplicationController
	def index
		@templates = RunningTemplate.all
	end

	def show
		@template = get_template(params[:id])
	end

	def new
		@template = RunningTemplate.new
	end

	def create
		@template = RunningTemplate.new(params[:template])
		if @template.save
			(1..@template.number_of_weeks).each do |sequence|
				week = RunningTemplateWeek.create!(running_template_id: @template.id,
												   sequence: sequence,
												   distance_percent: 100)
				(1..2).each do |sequence|
					RunningTemplateWorkout.create(running_template_week_id: week.id)
				end
			end

			redirect_to template_path(@template.id)
		else
			render 'new'
		end

	end

	def edit
		@template = get_template(params[:id])
	end

	def update
		@template = get_template(params[:id])
		if !@template.update_attributes(params[:template])
			render 'edit'
		else
			redirect_to template_path(@template.id)
		end
	end

	def destroy
		@template = get_template(params[:id])
		if @template.delete
			redirect_to templates_path
		else
			render 'delete'
		end
	end

	def new_instance
		@template = get_template(params[:id])
		@athletes = Athlete.all
	end

	def create_instance
		@template = get_template(params[:id])
		@athlete = Athlete.find(params[:athlete])

		schedule = []
		params[:day].each do |key, day|
			if day[:type] == "easy"
				schedule[key.to_i] = day[:context].to_f / 100
			else 
				schedule[key.to_i] = day[:type]
			end
		end

		@template.generate(@athlete, params[:race_date].to_date, schedule)
		redirect_to templates_path
	end


	private
		def get_template(id)
			if RunningTemplate.exists?(id)
				RunningTemplate.find(id)
			else
				redirect_to '/404'
			end
		end
end

app/helpers/running_template_helper.rb
module RunningTemplateHelper
	def edit_week(template, week)
		template_path(template) << "/weeks/#{week.sequence}/edit"
	end

	def update_week(template, week)
		template_path(template) << "/weeks/#{week.sequence}"
	end
end

app/views/running_templates/_form.html.erb
<div class="control-group">
	<label class="control-label" for="name">Template Name: </label>
	<div class="controls">
		<input type="text" id="name" name="template[name]" value="<%=template.name%>"></input>
	</div>
</div>
<div class="control-group">
	<label class="control-label" for="name">Distance</label>
	<div class="controls">
		<input type="text" class="span1" id="distance" name="template[distance]" value="<%= template.distance%>"></input>
		<select class="span1"><option value="1">Miles</option></select>
	</div>
</div>
<div class="control-group">
	<label class="control-label" for="number_of_weeks">Number of Weeks</label>
	<div class="controls">
		<input type="number" class="span1" id="number_of_weeks" name="template[number_of_weeks]" value="<%= template.number_of_weeks %>"></input>
	</div>
</div>
<div class="control-group">
	<label class="control-label" for="runs_per_week">Runs Per Week</label>
	<div class="controls">
		<input type="number" class="span1" id="runs_per_week" name="template[runs_per_week]" value="<%= template.runs_per_week %>"></input>
	</div>
</div>
<div class="control-group">
	<label class="control-label" for="name">Distance per Week</label>
	<div class="controls">
		<input type="number" class="span1" id="distance_per_week" name="template[distance_per_week]" value="<%= template.distance_per_week%>"></input>
		<select class="span2" name="distance_type" id="distance_type">
			<% render 'shared/distance_type_options' %>
		</select>
	</div>
</div>
<div class="form-actions">
  	<button type="submit" class="btn btn-primary">Save changes</button>
  	<a class="btn" href="<% if template.id.nil? %> <%= templates_path %> <% else %> <%= template_path(template) %> <% end %>">Cancel</a>
</div>

app/views/running_templates/edit.html.erb
<%= render 'shared/athlete_nav' %>
<%= render 'shared/error_messages', errors:@errors %>
<div class="row">
	<div class="span12">
		<ul class="breadcrumb">
		  <li><a href="<%= templates_path  %>">Templates</a> <span class="divider">-</span></li>
		  <li><a href="<%= template_path(@template) %>"><%= @template.name %></a> <span class="divider">-</span></li>
		  <li><a href="<%= edit_template_path(@template) %>">Edit</a></li>
		</ul>
	</div>
	<div class="span6 offset4">
		<%= form_tag template_path(@template), method: "put", :class => "form-horizontal" do %>
			<legend>Edit <%= @template.name %></legend>
			<%= render 'form', template:@template %>
		<% end %>
	</div>
</div>

app/views/running_templates/index.html.erb
<%= render 'shared/athlete_nav' %>

<div class="row">
	<div class="span12">
		<ul class="breadcrumb">
		  <li><a href="<%= templates_path %>">Templates</a> <span class="divider"></span></li>
		</ul>
	</div>
	<div class="pull-right">
		<a class="btn btn-large btn-success" href="<%= new_template_path %>"><i class="icon-plus icon-white"></i> Create Template</a>
	</div>
</div>
<div class="row">
	<div class="span12">
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th>Name</th> 
					<th>Distance</th> 
					<th>Distance Per Week</th> 
					<th>Level</th>
					<th>Weeks</th>
					<th>Runs Per Week</th>
				</tr>
			</thead>
			<tbody>
			<% @templates.each do |template| %>
				
				<tr>
						<td><%= template.name %></td>
						<td><%= template.distance %></td>
						<td><%= template.distance_per_week %></td>
						<td><%= template.level %></td>
						<td><%= template.number_of_weeks %></td>
						<td><%= template.runs_per_week %></td>
						<td><a href="<%= template_path(template.id) %>">Details</a></td>
						<td><a href="<%= new_instance_url(:id => template.id) %>">Generate</a></td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/running_templates/new.html.erb
<%= render 'shared/athlete_nav' %>
<%= render 'shared/error_messages', errors:@errors %>
<div class="row">
	<div class="span12">
		<ul class="breadcrumb">
		  <li><a href="<%= templates_path  %>">Templates</a> <span class="divider">-</span></li>
		  <li><a href="<%= new_template_path %>">New</a></li>
		</ul>
	</div>
	<div class="span6 offset4">
		<%= form_tag templates_path(@template), method: "post", :class => "form-horizontal" do %>
			<legend>New Template</legend>
			<%= render 'form', template:@template %>
		<% end %>
	</div>
</div>

app/views/running_templates/new_instance.html.erb
<%= render 'shared/athlete_nav' %>
<%= render 'shared/error_messages', errors:@errors %>
<div class="row">
	<div class="span12">
		<ul class="breadcrumb">
		  <li><a href="<%= templates_path  %>">Templates</a> <span class="divider">-</span></li>
		  <li><a href="<%= new_instance_url(:id => @template.id) %>">Generate <%= @template.name %></a></li>
		</ul>
	</div>
	<div class="span8 offset2">
		<%= form_tag create_instance_url(:id => @template.id), method: "post", :class => "form-horizontal" do %>
			<legend>Generate instance of <%= @template.name %></legend>
			<div class="control-group">
				<label class="control-label" for="athlete">Athlete: </label>
				<div class="controls">
					<select name="athlete" id="athlete">
						<% @athletes.each do |athlete| %>
							<option value="<%= athlete.id %>"><%= athlete.name %></option>
						<% end %>
					</select>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="race_date">Race Date:</label>
				<div class="controls">
					<input type="date" name="race_date" id="race_date"></input>
				</div>
			</div>
			<% (1..7).each do |day| %>
			<div class="control-group">
				<label class="control-label" for="day[<%= day - 1 %>]"><%= day_of_week(day % 7) %></label>
				<div class="controls">		
					<select class="span2" name="day[<%= day - 1 %>][type]">
						<option value="workout1">Primary Workout</option>
						<option value="workout2">Secondary Workout</option>
						<option value="easy">Easy Day</option>
						<option value="off" selected="selected">Off Day</option>
					</select>
					<input class="span1 offset5" type="number" min="0" max="100" size="3" name="day[<%= day - 1%>][context]"></input>
					<span class="add-on">%</span>
				</div>
			</div>
			<% end %>
			<div class="form-actions">
			  	<button type="submit" class="btn btn-primary">Save changes</button>
			  	<a type="button" class="btn" href="<%= templates_path  %>">Cancel</a>
			</div>
		<% end %>
	</div>
</div>

app/views/running_templates/show.html.erb
<%= render 'shared/athlete_nav' %>

<div class="row">
	<div class="span12">
		<ul class="breadcrumb">
		  <li><a href="<%= templates_path  %>">Templates</a> <span class="divider">-</span></li>
		  <li><a href="<%= template_path(@template) %>"><%= @template.name %></a> <span class="divider"></span></li>
		</ul>
		<div class="row">
			<div class="span4">
				<p>Name: <%= @template.name %></p>
				<p>Distance: <%= @template.distance %> Miles </p>
				<p>Level: <%= @template.level %></p>
			</div>
			<div class="span4">
				<p>Number of Weeks: <%= @template.number_of_weeks %></p>
				<p>Distance Per Week: <%= @template.distance_per_week %></p>
				<p>Runs Per Week: <%= @template.runs_per_week %></p>
			</div>
			<div class="span2">
				<a class="btn btn-small" href="<%= edit_template_path(@template) %>"> 
					<i class="icon-pencil"></i>
					 Edit 
				</a>
				<a class="btn btn-small" href="<%= template_path(@template) %>" data-method="delete" rel="nofollow" data-confirm="Are you sure?" title="Confirm delete <%= @template.name %>"> 
					<i class="icon-remove"></i>
					 Delete 
				</a>
			</div>
		</div>
		<% @template.running_template_weeks.each do |week| %>
		<h3>Week <%= week.sequence %> - <%= week.distance_percent %> % <%= link_to 'Edit', edit_week(@template, week) %></h3>
		<div class="row">
			<ul class="unstyled" style="border-top:solid;1px;">
				<% week.running_template_workouts.each do |workout| %>
				<li style="display:inline">
					<div class="span4">
						<h5><%= workout.description %> - <%= workout.total_distance %> <%= DistanceType.toString(workout.distance_type) %></h5>
						<ul class="unstyled">
						<% workout.running_template_workout_legs.each do |leg| %>
							<li>
							<% if !leg.repetitions.nil? %>
								<%= leg.repetitions %> x 
							<% end %>
							<%= leg.distance %> <%= DistanceType.toString(leg.distance_type) %> @ <%= PaceType.toString(leg.pace_type) %> pace
							<% if !leg.recovery.nil? %>
								w/ <%= leg.recovery %>s recovery
							<% end %>
							</li>
						<% end %>
						</ul>
					</div>
				</li>
				<% end %>
			</ul>
		</div>
		<% end %>
	</div>
</div>