config/routes.rb
Bulleit::Application.routes.draw do
  root :to => "pages#home"
  get "/login" => "oauth#login"
  get "/authorize" => "oauth#authorize"
  post "/athletes/create" => "athletes#create"
  get "/athletes/history" => "athletes#history", :as => "new_history"
  post "/athletes/history" => "athletes#create_history", :as=> "create_history"
  get "/athletes/goal" => "athletes#goal", :as => "new_goal"
  post "/athletes/goal" => "athletes#create_goal", :as => "create_goal"
  match "signout", to: 'oauth#destroy', via: :delete

  get '/schedule' => "schedule#schedule"
  get '/schedule/current' => "schedule#current_week"
  get '/templates/:id/generate' => "running_templates#new_instance", :as => "new_instance"
  post '/templates/:id/generate' => "running_templates#create_instance", :as => "create_instance"

  resources :templates, :controller => :running_templates do
    resources :weeks, :controller => :running_template_weeks, :only => [:edit, :update]
  end

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  attr_accessible :email, :name, :user_name, :access_token, :fb_user_id
  has_many :schedule_weeks
  has_many :goals
  has_one  :running_history
  has_many :training_paces
  has_many :race_histories

  before_save :create_remember_token

  def today
  	return self.workouts.find_by_date(Date.today)
  end

  def schedule
    return self.schedule_weeks
  end


  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
	def create
		@athlete = Athlete.new(name:params[:name],
							   fb_user_id:params[:fb_user_id],
							   email:params[:email],
							   user_name:params[:user_name],
							   access_token:params[:access_token])

		if @athlete.save
			@running_history = RunningHistory.new(athlete_id: @athlete.id,
												  distance_per_week: params[:distance_per_week],
												  distance_type: params[:distance_type], 
												  runs_per_week: params[:runs_per_week])
			if @running_history.save
				sign_in @athlete
				redirect_to new_history_url
				return
			end
		end
		render 'new'
	end

	def history
		@athlete = Athlete.find(current_user.id)
		@race_history = RaceHistory.new
	end

	def create_history
		@athlete = Athlete.find(current_user.id)

		params[:race].each do |sequence, race|
			if !race[:name].nil?
				RaceHistory.create(name: race[:name],
								   race_type: race[:race_type],
								   race_date: race[:race_date],
								   results: race[:results],
								   athlete_id: @athlete.id)
			end
		end
		redirect_to new_goal_url
	end

	def new_goal

	end

	def create_goal
		@athlete = Athlete.find(current_user.id)
		create_training_paces(@athlete)


		@goal = Goal.new(name: params[:name],
						 race: params[:race],
						 date: params[:date],
						 race_type: params[:race_type],
						 goal_time: params[:goal_time],
						 athlete_id: @athlete.id)
		if !@goal.save
			render 'new_goal'
		else
			template = RunningTemplate.first
			template.generate(@athlete, @goal.date, [ 0.40, "off", "workout1", 0.30, "off", "workout2", 0.30])
			redirect_to root_path
		end
	end

	private
		def create_training_paces(athlete)
			TrainingPace.create(athlete_id:athlete.id,
					pace_type:0,
					min_pace:"7:45",
					max_pace:"8:30")
			TrainingPace.create(athlete_id:athlete.id,
								pace_type:1,
								min_pace:"7:03")
			TrainingPace.create(athlete_id:athlete.id,
								pace_type:2,
								min_pace:"6:40")
			TrainingPace.create(athlete_id:athlete.id,
								pace_type:3,
								min_pace:"6:10")
		end
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/goal.html.erb
<%= render 'shared/athlete_nav' %>
<%= render 'shared/error_messages', errors:@errors %>
<div class="row">
	<div class="span6 offset2">
		<%= form_tag create_goal_url, method: "post"  do %>
		<legend>Race Goal</legend>
		<div class="control-group">
			<label class="control-label" for="name">Goal Name: </label>
			<div class="controls">
				<input type="text" id="name" name="name"></input>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="race">Race: </label>
			<div class="controls">
				<input type="text" id="race" name="race"></input>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="race_type">Distance: </label>
			<div class="controls">
				<select class="span2" name="race_type" id=="race_type">
					<option value="<%= RaceType::FIVEK %>"><%= RaceType::toString(RaceType::FIVEK) %></option>
					<option value="<%= RaceType::TENK %>"><%= RaceType::toString(RaceType::TENK) %></option>
					<option value="<%= RaceType::HALFMARATHON %>"><%= RaceType::toString(RaceType::HALFMARATHON) %></option>
					<option value="<%= RaceType::MARATHON %>"><%= RaceType::toString(RaceType::MARATHON) %></option>
				</select>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="date">Race Date: </label>
			<div class="controls">
				<input class="span2" type="date" id="date" name="date">
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="goal_time">Goal Time: </label>
			<div class="controls">
				<input class="span2" type="text" id="goal_time" name="goal_time">
			</div>
		</div>
		<div class="form-actions">
		  	<button type="submit" class="btn btn-primary">Save changes</button>
		  	<a class="btn" href="/">Cancel</a>
		</div>
		<% end %>
	</div>
</div>

app/views/athletes/history.html.erb
<%= render 'shared/athlete_nav' %>
<%= render 'shared/error_messages', errors:@errors %>
<div class="row">
	<div class="span6 offset2">
		<%= form_tag create_history_url, method: "post"  do %>
			<legend>Athlete Race History</legend>
			<div class="control-group">
				<label class="control-label" for="recent_races"></label>
				<div class="controls">
					<input type="checkbox" name="never_raced"> I have never run a race before</input>
				</div>
			</div>

			<table class="table table-striped">
				<thead>
					<th>Name</th>
					<th>Distance</th>
					<th>Date</th>
					<th>Results</th>
				</thead>
				<tbody>
					<% (0..4).each do |row| %>
						<tr>
							<td><input class="span3" type="text" id="race[<%= row %>]name" name="race[<%= row %>]name"></input></td>
							<td><select class="span2" name="race[<%= row %>]race_type" id=="race[<%= row %>]race_type">
								<option value="<%= RaceType::FIVEK %>"><%= RaceType::toString(RaceType::FIVEK) %></option>
								<option value="<%= RaceType::TENK %>"><%= RaceType::toString(RaceType::TENK) %></option>
								<option value="<%= RaceType::HALFMARATHON %>"><%= RaceType::toString(RaceType::HALFMARATHON) %></option>
								<option value="<%= RaceType::MARATHON %>"><%= RaceType::toString(RaceType::MARATHON) %></option>
							</select></td>
							<td><input class="span2" type="date" id="race[<%= row %>]race_date" name="race[<%= row %>]date"></input></td>
							<td><input class="span2" type="text" id="race[<%= row %>]results" name="race[<%= row %>]result"></input></td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<div class="form-actions">
			  	<button type="submit" class="btn btn-primary">Save changes</button>
			  	<a class="btn" href="/">Cancel</a>
			</div>
		<% end %>
	</div>
</div>
	

app/views/athletes/new.html.erb
<%= render 'shared/athlete_nav' %>
<%= render 'shared/error_messages', errors:@errors %>
<div class="row">
	<div class="span6 offset4">
		<%= form_tag athletes_create_path(@athlete), method: "post"  do %>
			<legend>New Athlete Profile</legend>
			<div class="control-group">
				<label class="control-label" for="user_name">User Name: </label>
				<div class="controls">
					<input type="text" id="user_name" name="user_name"></input>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="email">Email Address: </label>
				<div class="controls">
					<input type="email" id="email" name="email"></input>
				</div>
			</div>		
			<div class="control-group">
				<label class="control-label" for="runs_per_week">Runs per Week</label>
				<div class="controls">
					<input type="number" min="0" class="span2" id="runs_per_week" name="runs_per_week"></input>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="name">Distance per Week</label>
				<div class="controls">
					<input type="number" min="0" class="span2" id="distance_per_week" name="distance_per_week"></input>
					<select class="span2" name="distance_type" id="distance_type">
						<%= render 'shared/distance_type_options' %>
					</select>
				</div>
			</div>
			<input type="hidden" name="fb_user_id" value="<%= @fb_user_id %>"/>
			<input type="hidden" name="name" value="<%= @name %>"/>
			<input type="hidden" name="access_token" value="<%= @access_token %>"/>
			<div class="form-actions">
			  	<button type="submit" class="btn btn-primary">Save changes</button>
			  	<a class="btn" href="/">Cancel</a>
			</div>
		<% end %>
	</div>
</div>
	