config/routes.rb
Bulleit::Application.routes.draw do
  root :to => "pages#home"
  get "/login" => "oauth#login"
  get "/authorize" => "oauth#authorize"
  post "/athletes/create" => "athletes#create"
  get "/athletes/history" => "athletes#history", :as => "new_history"
  post "/athletes/history" => "athletes#create_history", :as=> "create_history"
  get "/athletes/goal" => "athletes#goal", :as => "new_goal"
  post "/athletes/goal" => "athletes#create_goal", :as => "create_goal"
  match "signout", to: 'oauth#destroy', via: :delete

  get '/schedule' => "schedule#schedule"
  get '/schedule/current' => "schedule#current_week"
  get '/templates/:id/generate' => "running_templates#new_instance", :as => "new_instance"
  post '/templates/:id/generate' => "running_templates#create_instance", :as => "create_instance"

  resources :templates, :controller => :running_templates do
    resources :weeks, :controller => :running_template_weeks, :only => [:edit, :update]
  end

end

app/views/shared/_athlete_nav.html.erb
<% content_for :nav do %>
    <li>
    	<a href="<%= schedule_path %>">Schedule</a>
    </li>
  	<%= render "shared/login_logout" %>
<% end %>

app/views/shared/_distance_type_options.html.erb
<option value="<%= DistanceType::MILES %>"><%= DistanceType::toString(DistanceType::MILES) %></option>
<option value="<%= DistanceType::METERS %>"><%= DistanceType::toString(DistanceType::METERS) %></option>
<option value="<%= DistanceType::KILOMETERS %>"><%= DistanceType::toString(DistanceType::KILOMETERS) %></option>

app/views/shared/_error_messages.html.erb
<% if !errors.nil? && errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(errors.count, "error") %>.
    </div>
    <ul>
    <% errors.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_logged_out_nav.html.erb
<% content_for :nav do %>
  	<%= render "shared/login_logout" %>
<% end %>

app/views/shared/_login_logout.html.erb
<li class="dropdown">  
  <% if signed_in? %>
	<a href="#"
      class="dropdown-toggle"
      data-toggle="dropdown">
      <%= current_user.user_name %>
      <b class="caret"></b>
	</a>
	<ul class="dropdown-menu">
  	<li>
  		<%= link_to "Sign out", signout_path, method: "delete" %>
  	</li>
	</ul>
  <% else %>
  <a href="/login">Log in</a>
  <% end %>
</li>